Replace Node.js Buffer and Stream API with Uint8Array and Web Streams API
AxisCommunications/media-stream-library-js pull request #1069
Opened 2024-12-05 08:49 UTC by steabert

Replace usage of Node.js Buffer and Stream API with Uint8Array and Web Streams API.
The latter are natively supported in the browser _and_ Node.js.

Reason for migration:
- browser compatibility packages for Node.js Buffer and Stream API are no longer maintained
- Node.js supports Uint8Array and Web Streams API

TODO:
- [ ] messages data field is Uint8Array
  - [ ] rtsp-parser
- [ ] components redesigned around Web Streams API

2025-01-08 13:24 UTC, lekoaf commented on player/esbuild.mjs
> +  target: 'es2015',
Just an observation, probably not relevant for you. In the latest version of esbuild, 0.24.2, you can use "es2024" as target.

2025-01-08 13:25 UTC, lekoaf commented on player/src/Container.tsx
> +  readonly children: any // styled-components type mismatch
:see_no_evil:

2025-01-08 13:41 UTC, lekoaf commented on streams/src/components/mp4-muxer/boxbuilder.ts
> +      const trak = this.trak(track)
Intentional misspelling?

2025-01-08 14:06 UTC, lekoaf commented on streams/src/components/mp4-muxer/isom.ts
>  // - store(buffer, offset) -> write the value to a buffer
Note to self: Continue here. :smiley:

2025-01-09 06:53 UTC, lekoaf commented on streams/src/components/mp4-muxer/isom.ts
> +  abstract copy(buffer: Uint8Array, offset: number): void
Learned something new today. Didn't know about `abstract` classes and methods. :smiley:

2025-01-09 07:10 UTC, lekoaf commented on streams/src/components/mp4-parser/parser.ts
> +  _push(chunk: Uint8Array): void {
Prefix with private instead of underscore? :thinking:

2025-01-09 07:18 UTC, lekoaf commented on streams/src/components/rtp/jpeg-depay.ts
> +  private _headers = {
Same here, and a lot of other places.

2025-01-09 07:24 UTC, lekoaf commented on streams/src/components/rtp/jpeg-headers.ts
> +  return new Uint8Array([0xff, 0xdd, 0x00, 4, dri >> 8, dri & 0xff])
Reading code like this while not knowing much about video parsing just makes me feel stupid. Am I supposed to know what theses hex codes mean or what `dri` is and what shifting it with 8 does?

To an "outsider", much of this code reads like I would expect minified and obfuscated code to look like. :laughing: 

Only one day away from the weekend... :beers:

2025-01-09 08:15 UTC, lekoaf commented on streams/src/components/rtsp/header.ts
> +  const [_rtspVersion, statusCode, _reasonPhrase] = startline.split(' ')
Why are you extracting variables you're not using?

2025-01-09 08:31 UTC, rikteg requested changes

2025-01-09 08:31 UTC, rikteg commented on streams/src/rtsp-jpeg-pipeline.ts
> +        `ws-rtsp-jpeg pipeline ended: downstream: ${down} upstream: ${up}`
```suggestion
        `rtsp-jpeg-pipeline ended: downstream: ${down} upstream: ${up}`
```
?

2025-01-09 08:31 UTC, rikteg commented on streams/tests/h264depay.test.ts
> +    /* eslint-enable */
Necessary? :)

2025-01-09 08:31 UTC, rikteg commented on streams/tests/rtsp-parser.test.ts
> +    // })
Remove?

2025-01-09 08:31 UTC, rikteg commented on streams/tests/rtsp-rtcp.fixtures.ts
> +  new Uint8Array([
Should perhaps also have custom formatting?

2025-01-09 08:31 UTC, rikteg commented on streams/tests/rtsp-sdp.test.ts
>  /* eslint-enable */
Needed?

2025-01-09 08:31 UTC, rikteg commented on streams/tests/ws-source.test.ts
> +      .then(() => console.log('deon'))
```suggestion
      .then(() => console.log('done'))
```
?

2025-01-09 08:49 UTC, lekoaf commented on streams/src/components/rtsp/rtp.ts
> +        12 + cSrcCount(packet) * 4 + 4 + extHeaderLength(packet) * 4
Do you trust Javascript to calculate this correctly without parentheses?

2025-01-09 08:52 UTC, lekoaf submitted a review, later dismissed
Well, overall the code looks fine. I trust that you test it thoroughly.

2025-01-09 11:55 UTC, steabert commented on streams/src/components/mp4-muxer/boxbuilder.ts
> +      const trak = this.trak(track)
The box is called "trak" (the identifier)

2025-01-09 11:56 UTC, steabert commented on streams/src/components/mp4-parser/parser.ts
> +  private _chunks: Uint8Array[] = []
You're right, I tried to simplify most of these by removing the underscore, I'll have another look. As you say, it's now clear through TypeScript.

2025-01-09 11:57 UTC, steabert commented on streams/src/components/rtp/jpeg-headers.ts
> +  return new Uint8Array([0xff, 0xdd, 0x00, 4, dri >> 8, dri & 0xff])
Much of this is legacy that I did not want to touch, so yes, legibility isn't that great in a lot of places.

2025-01-09 12:03 UTC, steabert commented on streams/src/components/rtsp/rtp.ts
> +        12 + cSrcCount(packet) * 4 + 4 + extHeaderLength(packet) * 4
Yes 😄

2025-01-09 12:15 UTC, steabert commented on streams/src/components/rtsp/header.ts
> +  const [_rtspVersion, statusCode, _reasonPhrase] = startline.split(' ')
I thought it would be nice as documention-like placeholders.

2025-01-09 16:16 UTC, steabert commented on streams/src/components/rtsp/session.ts
> +        headers: { ...this.headers.OPTIONS },
We potentially modify the headers of a request, so this prevents modifying the default headers.

2025-01-09 16:16 UTC, steabert commented on streams/src/components/rtsp/session.ts
> +        headers: { ...this.headers.DESCRIBE },
same

2025-01-09 16:18 UTC, steabert commented
@lekoaf @rikteg I fixed all comments (even though I didn't always write a reply), if I didn't then I responded why I didn't change.

2025-01-10 13:38 UTC, victoringvarsson approved these changes

2025-01-10 13:39 UTC, merged

2025-01-10 13:55 UTC, oskbor commented
lgtm, ship it