feat: es5 player example
AxisCommunications/media-stream-library-js pull request #545
Opened 2020-11-17 13:51 UTC by lekoaf

This is very much untested code on my side, but it's based on @cwillison94 excellent effort in #459.

I don't have access to windows and IE11, so I'll take his word for it that this actually works.

Unfortunately I couldn't continue on his PR since he pushed it straight to master and I had not push rights there.

2021-01-13 15:59 UTC, steabert commented
LGTM. @cwillison94 any review comment on this? If not then I can merge this.

2021-01-13 16:16 UTC, cwillison94 approved these changes

2021-01-14 07:08 UTC, lekoaf commented
> I would rather see the original author in the commit, can you cherry-pick and add your changes on top @lekoaf ?

I'm not sure. Can I? I started this PR because I couldn't add anything to @cwillison94 PR since he used his master branch instead of a feature branch.

2021-04-04 15:16 UTC, steabert commented
Starting a new PR is no problem. But you can checkout someone's PR locally on a new branch, and then add new commits on top, and push as a new PR. That way, the original author will be also mentioned (but you will be the committer).

Something like:
```
git fetch https://github.com/cwillison94/media-stream-library-js.git d16fb67f9f80fdd655c3343c2608521139d0f246
git checkout -b es5-example FETCH_HEAD
```
Then add your changes on top as new commits, or even as amended commit (even then, author is preserved).

Since you already have the `es5-example` locally, you'll probably better save your stuff on a branch before doing this, like so:
```
git checkout es5-example
git checkout -b es5-example-backup
git fetch https://github.com/cwillison94/media-stream-library-js.git d16fb67f9f80fdd655c3343c2608521139d0f246
git checkout -B es5-example FETCH_HEAD
```

2021-06-21 14:19 UTC, TannerGabriel requested changes
Great example, but there are still a few things that could be improved.

2021-06-21 14:19 UTC, TannerGabriel commented on examples/browser/camera/simple-es5-player.js
> +  var pipeline
The variable name is repeated across the file. This could be confusing but is not a big deal.

2021-06-21 14:19 UTC, TannerGabriel commented on examples/browser/camera/simple-es5-player.html
> +	  <script src="rtsp-player.js"></script>
Why is it importing the `rtsp-player.js` script instead of the `simple-es5-player.js` script featured in the PR?

2021-06-21 14:19 UTC, TannerGabriel commented on examples/browser/camera/simple-es5-player.js
> +    var config = {}
Variable could be directly initialized:

```
let config = {
      ws: {
        uri: 'ws://' + host + '/rtsp-over-websocket',
      },
      rtsp: {
        uri: 'rtsp://' + host + '/axis-media/media.amp?videocodec=' + encoding,
      },
      mediaElement: mediaElement,
 }
```

2023-03-18 14:18 UTC, closed without merging