fix: update copyright year
AxisCommunications/media-stream-library-js pull request #724
Opened 2023-01-25 10:18 UTC by barnomasoz

Closes #694

### Describe your changes

Change copyright year from 2022 to 2023

### Issue ticket number and link

- Fixes #694

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have verified that the code builds perfectly fine on my local system
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have verified that my code follows the style already available in the repository
- [ ] I have made corresponding changes to the documentation

2023-01-25 15:22 UTC, lekoaf approved these changes

2023-02-01 15:27 UTC, steabert requested changes
There are some MacOS M1 zip files that came along with this commit that shouldn't be here.

However, you're welcome to make a separate commit to support other binary formats 😄

2023-02-01 16:36 UTC, barnomasoz commented
> There are some MacOS M1 zip files that came along with this commit that shouldn't be here.
> 
> However, you're welcome to make a separate commit to support other binary formats 😄

Excluded them from this PR. New PR for adding binaries is here: [727](https://github.com/AxisCommunications/media-stream-library-js/pull/727)

2023-03-18 13:44 UTC, steabert approved these changes

2023-03-18 13:44 UTC, merged